name: Build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - mdl-1.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 11
          cache: 'npm'
      - name: npm install, build and test
        run: |
          npm install
          npm run test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/material.js
            dist/material.min.js
            dist/material.min.js.map
