name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: runner / reviewdog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.{js,ts}
          files_ignore: |
            third_party/**
      - uses: actions/setup-node@v4
        with:
          node-version: 11
          cache: 'npm'
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEW_DOG_PAT }}
        with:
          github_token: ${{ secrets.REVIEW_DOG_PAT }}
          reporter: github-pr-review
          level: error
          eslint_flags: ${{ steps.changed-files.outputs.all_changed_files }}
